name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        POETRY_PYPI_TOKEN_PYPI=$(curl -s -X POST \
          "https://pypi.org/_/oidc/github/AlbertUnruh/gypt-matplotlib/" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}")
        poetry publish --build -r testpypi
